{"name": "test_assertions", "status": "broken", "statusDetails": {"message": "AttributeError: 'async_generator' object has no attribute 'goto'", "trace": "page = <async_generator object page at 0x000001F7CE373ED0>\nenv_vars = {'password': 'User@123', 'url': 'https://worldamenities.com/', 'username': 'user123@gmail.com'}\n\n    @pytest.mark.smoke\n    @pytest.mark.asyncio\n    async def test_assertions(page, env_vars):\n        url = env_vars['url']\n    \n        login_page = LoginPage(page)\n>       await login_page.goto(url)\n\ntests\\test_WAWorld.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.LoginPage.LoginPage object at 0x000001F7CE3AE630>, url = 'https://worldamenities.com/'\n\n    async def goto(self, url: str):\n>       await self.page.goto(url)\nE       AttributeError: 'async_generator' object has no attribute 'goto'\n\npages\\LoginPage.py:28: AttributeError"}, "start": 1720145271252, "stop": 1720145271252, "uuid": "48a422b9-08e5-4a5a-b9a0-dc0b9b7c8aff", "historyId": "6d170851127fd59c90368cc8fc6a73af", "testCaseId": "6d170851127fd59c90368cc8fc6a73af", "fullName": "tests.test_WAWorld#test_assertions", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_WAWorld"}, {"name": "host", "value": "Feuji-V005L-R"}, {"name": "thread", "value": "21004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_WAWorld"}]}