{"name": "test_newtabActions", "status": "broken", "statusDetails": {"message": "AttributeError: 'async_generator' object has no attribute 'goto'", "trace": "page = <async_generator object page at 0x000001E46D915560>, context = <async_generator object context at 0x000001E46D9153C0>\nenv_vars = {'password': 'User@123', 'url': 'https://worldamenities.com/', 'username': 'user123@gmail.com'}\n\n    @pytest.mark.smoke\n    @pytest.mark.asyncio\n    async def test_newtabActions(page, context, env_vars):\n        url = env_vars['url']\n        username = env_vars['username']\n        password = env_vars['password']\n    \n        login_page = LoginPage(page)\n>       await login_page.goto(url)\n\ntests\\test_WAWorld.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.LoginPage.LoginPage object at 0x000001E46D949430>, url = 'https://worldamenities.com/'\n\n    async def goto(self, url: str):\n>       await self.page.goto(url)\nE       AttributeError: 'async_generator' object has no attribute 'goto'\n\npages\\LoginPage.py:28: AttributeError"}, "start": 1720144699501, "stop": 1720144699501, "uuid": "b9526966-7538-4650-88e7-c0009e7ccda5", "historyId": "41a2b5fe3c3583c0f106f5f8d269c4e9", "testCaseId": "41a2b5fe3c3583c0f106f5f8d269c4e9", "fullName": "tests.test_WAWorld#test_newtabActions", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_WAWorld"}, {"name": "host", "value": "Feuji-V005L-R"}, {"name": "thread", "value": "16552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_WAWorld"}]}